In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
# 讀取糖尿病資料集
diabetes = datasets.load_diabetes()

# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(diabetes.data, diabetes.target, test_size=0.2, random_state=4)

# 建立一個線性回歸模型
regr = linear_model.LinearRegression()

# 將訓練資料丟進去模型訓練
regr.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = regr.predict(x_test)

In [3]:
print(regr.coef_)

[  33.40877011 -292.24672884  481.07153405  369.06269614 -966.37849405
  589.81383056  232.61924401  288.3263166   802.72704593   37.81285219]


In [4]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 2939.42


In [5]:
# 讀取糖尿病資料集
diabetes = datasets.load_diabetes()

# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(diabetes.data, diabetes.target, test_size=0.2, random_state=4)

# 建立一個線性回歸模型
lasso = linear_model.Lasso(alpha=1.0)

# 將訓練資料丟進去模型訓練
lasso.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = lasso.predict(x_test)

In [6]:
# 印出各特徵對應的係數，可以看到許多係數都變成 0，Lasso Regression 的確可以做特徵選取
lasso.coef_

array([  0.        ,  -0.        , 321.203877  ,  57.74744332,
         0.        ,   0.        ,  -0.        ,   0.        ,
       332.41817196,   0.        ])

In [7]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 3505.84


In [8]:
# 讀取糖尿病資料集
diabetes = datasets.load_diabetes()

# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(diabetes.data, diabetes.target, test_size=0.2, random_state=4)

# 建立一個線性回歸模型
ridge = linear_model.Ridge(alpha=1.0)

# 將訓練資料丟進去模型訓練
ridge.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = regr.predict(x_test)

In [9]:
# 印出 Ridge 的參數，可以很明顯看到比起 Linear Regression，參數的數值都明顯小了許多
print(ridge.coef_)

[  48.8125786   -85.49511577  270.22532535  201.91767903   17.41308665
  -19.04346706 -136.47737574  122.26503311  247.60074795   95.59855598]


In [10]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 2939.42


In [11]:
#可以看見 LASSO 與 Ridge 的結果並沒有比原本的線性回歸來得好， 這是因為目標函數被加上了正規化函數，
#讓模型不能過於複雜，相當於限制模型擬和資料的能力。
#因此若沒有發現 Over-fitting 的情況，是可以不需要一開始就加上太強的正規化的。

In [13]:
# Day 40 HW
boston = datasets.load_boston()

In [14]:
# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.55, random_state=4)

# 建立一個線性回歸模型
regr = linear_model.LinearRegression()

# 將訓練資料丟進去模型訓練
regr.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = regr.predict(x_test)

In [15]:
print(regr.coef_)

[-9.61105458e-02  4.91212632e-02 -8.25054675e-03  2.89455150e+00
 -1.53095931e+01  3.59132934e+00 -1.27736960e-03 -1.33501194e+00
  3.03085373e-01 -1.28619946e-02 -7.77929255e-01  1.09061569e-02
 -4.68971237e-01]


In [16]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 25.62


In [18]:
# 預測值與實際值的差距，使用 R2
print("Mean squared error: %.2f"
      % r2_score(y_test, y_pred))

Mean squared error: 0.74


In [34]:
# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.55, random_state=4)

# 建立一個線性回歸模型
lasso = linear_model.Lasso(alpha=0.1)

# 將訓練資料丟進去模型訓練
lasso.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = lasso.predict(x_test)

In [35]:
# 印出各特徵對應的係數，可以看到許多係數都變成 0，Lasso Regression 的確可以做特徵選取
lasso.coef_

array([-0.08356576,  0.05011134, -0.0591417 ,  0.69389869, -0.        ,
        3.36716214, -0.01570238, -1.09333029,  0.29976807, -0.01581672,
       -0.62531116,  0.01216671, -0.51256442])

In [36]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 27.35


In [37]:
# 預測值與實際值的差距，使用 R2
print("Mean squared error: %.2f"
      % r2_score(y_test, y_pred))

Mean squared error: 0.72


In [38]:
from sklearn.linear_model import Ridge
rg = Ridge(alpha = 0.1)

In [39]:
# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.55, random_state=4)

# 將訓練資料丟進去模型訓練
rg.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = rg.predict(x_test)

In [40]:
# 印出各特徵對應的係數，可以看到許多係數都變成小，Ridge Regression 的確可做 w 優化
rg.coef_

array([-9.53265315e-02,  4.91413387e-02, -1.55607891e-02,  2.82457137e+00,
       -1.34629954e+01,  3.59721277e+00, -3.60920787e-03, -1.31175731e+00,
        3.01438588e-01, -1.31351769e-02, -7.60358386e-01,  1.10694063e-02,
       -4.70951336e-01])

In [41]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 25.68


In [42]:
# 預測值與實際值的差距，使用 R2
print("Mean squared error: %.2f"
      % r2_score(y_test, y_pred))

Mean squared error: 0.74


In [ ]:
# 可見原本資料本身就沒有 overfitting 可以不一定要做 ridge or lasso